### ISSUE TITLE
Random crashing

### ISSUE THREAD

**Issue by vantech14** [dehsgr/node-red-contrib-alphaess#3] opened 2022-08-15 14:20 UTC
Hi,

I am on version 1.5.4, and notice daily crashes. Node-red runs perfectly, then stops, requiring a manual restart (i am using home assistant).

Disabling alpha ess fixes the issue. 

Any help / logs required please let me know. 

Great app!

Thanks.

**Comment by dehsgr** [comment] 2022-08-15 14:31
@vantech14 please update to v1.5.5 and check if the issue persists…

**Comment by dehsgr** [comment] 2022-08-15 14:32
Possibly a duplicate of issue #2.

**Comment by vantech14** [comment] 2022-08-15 14:41
@dehsgr this version is not showing in Node-red, there is no option to update. 

Thanks.

**Comment by dehsgr** [comment] 2022-08-15 18:00
@vantech14 please try again. Flows weren‘t updated with last publish.

**Comment by vantech14** [comment] 2022-08-15 20:42
Hi,

I can see the update but get a new error which refuses to let me update the node. Error in this post relates to the email node, but the same error applies to the alpha node. 

https://github.com/hassio-addons/addon-node-red/issues/1424

**Comment by dehsgr** [comment] 2022-08-15 20:48
@vantech14 I assume the update error is related to your system/Node-RED install. There would no way for me to fix this.

Nevertheless you could post the whole update log. I‘ll try to help you further…

**Comment by vantech14** [comment] 2022-08-18 09:41
Hi @dehsgr 

Fixed the issue and I've upgraded. Unfortunately the integration keeps dropping are remotes 0 values. Disabling the node and re-enabling the integration fixes the issue for several hours. 

Thanks.

**Comment by dehsgr** [comment] 2022-08-18 09:46
Can you clarify, what you mean with "Unfortunately the integration keeps dropping are remotes 0 values"? Do you get any errors? Do you have a stable connection? I'm not aware of such an issue...

**Comment by vantech14** [comment] 2022-08-18 17:25
Here is a snapshot: 

![image](https://user-images.githubusercontent.com/76781626/185457030-f4a31524-604f-45b4-bf58-1bc246d8080b.jpeg)

The values are coming back as zero.

**Comment by vantech14** [comment] 2022-08-18 17:39
@dehsgr interestingly if you reboot node red it doesn't fix the issue. You need to disable the node, save, re-enable and then it works again

**Comment by dehsgr** [comment] 2022-08-18 17:43
@vantech14 can you show your settings to me too? You might anonymize relevant parts. And I would like you to provide a log (best: verbose) when the issue occurs.

**Comment by vantech14** [comment] 2022-08-18 17:47
@dehsgr i am running NR in Home Assistant so unsure where the logs are configured and stored?

**Comment by dehsgr** [comment] 2022-08-18 17:49
@vantech14 I cannot answer this. Maybe the HA documentation helps here…

**Comment by vantech14** [comment] 2022-08-18 17:56
@dehsgr 

Here you go: 

18 Aug 18:34:55 - [warn] [alphaess-monitoring:Alpha ESS Smile B3] There was an error fetching realtime data for AL700XXXXXX: Malformed or empty response!
18 Aug 18:34:55 - [error] [ha-entity:Battery State of Charge] State must be defined.
18 Aug 18:34:59 - [info] [alphaess-monitoring:Alpha ESS Smile B3] Renewing token...
18 Aug 18:35:00 - [warn] [alphaess-monitoring:Alpha ESS Smile B3] There was an error fetching realtime data for AL700XXXXXXX: Malformed or empty response!
18 Aug 18:35:00 - [error] [ha-entity:Battery State of Charge] State must be defined.
18 Aug 18:35:00 - [warn] [alphaess-monitoring:Alpha ESS Smile B3] There was an error during login operation into Alpha ESS monitoring portal: TypeError: Cannot read properties of null (reading 'AccessToken')

We got the following unprocessable body:
{"code":102,"info":"Token is Expire","data":null}
18 Aug 18:35:04 - [info] [alphaess-monitoring:Alpha ESS Smile B3] Renewing token...
18 Aug 18:35:05 - [warn] [alphaess-monitoring:Alpha ESS Smile B3] There was an error during login operation into Alpha ESS monitoring portal: TypeError: Cannot read properties of null (reading 'AccessToken')

I am using the same username and password i always have, with the serial number of the battery itself. These settings have worked flawlessly for months.

**Comment by dehsgr** [comment] 2022-08-18 18:17
@vantech14 okay. So there is some issue while the authentication token is renewed. I suggest that you completely remove the alpha node once. Afterwards you safe/publish your flow. Now try to drop a new node instance with a fresh configuration on your flow. I assume there could be some kind of wrong (old) data which are used for token renewal. But I‘m not sure. Token renewal works flawlessly here…

**Comment by vantech14** [comment] 2022-08-18 18:40
@dehsgr deleted the node, now when I re-add it, populate all fields, it throws a configuration error saying that "some nodes are not configured properly" are you sure you want to deploy?

**Comment by vantech14** [comment] 2022-08-18 18:45
@dehsgr however the node is working, and pulling data. The error remains. 

![image](https://user-images.githubusercontent.com/76781626/185470697-4389ddff-6850-4b64-9a06-c392925e3f9e.jpeg)

**Comment by dehsgr** [comment] 2022-08-18 18:51
I would like you to try to tick and untuck the backup fetch checkbox for getting rid of the configuration error. I‘ll try to fix this issue as soon as possible.

**Comment by vantech14** [comment] 2022-08-19 06:19
@dehsgr woke this morning and found the integration was having token issues again. This was after a fresh reinstall of the alpha node. 

Thanks.

**Comment by dehsgr** [comment] 2022-08-25 16:12
@vantech14 token renewal failure seems to be some specific on your site. No other people are reporting this. As already discussed I would like you to set node-red logging to verbose level and provide me such a log.

The "invalid property issue" is fixed now.

**Comment by vantech14** [comment] 2022-08-26 18:10
@dehsgr here is the log in debug. 

26 Aug 19:05:15 - [info] [alphaess-monitoring:Alpha ESS Smile B3] Renewing token...
26 Aug 19:05:15 - [debug] [alphaess-monitoring:Alpha ESS Smile B3] Fetching realtime data...
26 Aug 19:05:16 - [warn] [alphaess-monitoring:Alpha ESS Smile B3] There was an error during login operation into Alpha ESS monitoring portal: TypeError: Cannot read properties of null (reading 'AccessToken')

We got the following unprocessable body:
{"code":102,"info":"Token is Expire","data":null}
26 Aug 19:05:16 - [warn] [alphaess-monitoring:Alpha ESS Smile B3] There was an error fetching realtime data for AL700xxxxxx: Malformed or empty response!
26 Aug 19:05:16 - [debug] [alphaess-monitoring:Alpha ESS Smile B3] Processing data...
26 Aug 19:05:16 - [debug] [alphaess-monitoring:Alpha ESS Smile B3] Fetching hourly statistics...
26 Aug 19:05:16 - [debug] [alphaess-monitoring:Alpha ESS Smile B3] Fetching daily statistics...
26 Aug 19:05:16 - [error] [ha-entity:Battery State of Charge] State must be defined.
26 Aug 19:05:20 - [info] [alphaess-monitoring:Alpha ESS Smile B3] Renewing token...
26 Aug 19:05:20 - [debug] [alphaess-monitoring:Alpha ESS Smile B3] Fetching realtime data...
26 Aug 19:05:21 - [warn] [alphaess-monitoring:Alpha ESS Smile B3] There was an error during login operation into Alpha ESS monitoring portal: TypeError: Cannot read properties of null (reading 'AccessToken')

Thanks.

**Comment by dehsgr** [comment] 2022-08-29 11:49
@vantech14 I just commited a possible fix for your issue. So I would like you to manueally change your [alphaess-monitoring.js](https://github.com/dehsgr/node-red-contrib-alphaess/blob/main/alphaess-monitoring.js) with the current one from this repository. Afterwards I would like you to provide feedback if the isse persits or not. If this would fix your issue I will publish this fix to NPM. Otherwise I would like you to place an additional log.

**Comment by vantech14** [comment] 2022-08-29 15:53
@dehsgr done, will revert back in a few days with an update. Thanks!

**Comment by vantech14** [comment] 2022-09-03 08:46
@dehsgr the integration is still up and working fine. Your latest fix worked. Thanks again.

**Comment by vantech14** [comment] 2022-09-03 08:48
@dehsgr are you using this API / have you seen this? 

https://community.openenergymonitor.org/uploads/short-url/2qysTQ2mAaEEctdEIHXuaaofYIQ.pdf

**Comment by dehsgr** [comment] 2022-09-03 08:59
@vantech14 thanks for your feedback. I‘ll release the new package later. I‘ll use another API, not the one you linked. Your API requires a secret offered by AlphaESS…

**Comment by dehsgr** [comment] 2022-09-04 06:36
Published updated package now. Thanks for your input to for being able to fix this issue!

**Closed as completed by dehsgr** 2022-09-04 06:36 UTC
Labels: bug, help wanted, question
